[package]
name = "blockchain"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.97"
chrono = "0.4.40"
hex = "0.4.3"
log = "0.4.26"
num-bigint = "0.4.6"
once_cell = "1.20.3"
rs_merkle = "1.5.0"
sha2 = "0.10.8"
